# Generated by Django 3.2.8 on 2024-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachertopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.IntegerField(blank=True, max_length=11, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'teacher_topic',
                'managed': True,
            },
        ),
    ]
