# Generated by Django 3.2.8 on 2024-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_teachertopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertopic',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
